version: '3.8'

services:
  app:
    build:
      context: ./src/app
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    volumes:
      - .:/app